#useful reference: http://dan-blanchard.roughdraft.io/7045057-quicker-travis-builds-that-rely-on-numpy-and-scipy-using-miniconda
#useful reference: https://gist.github.com/dan-blanchard/7045057    

language: python
python:
    - "3.4"
before_install:
    - pip install pytest pytest-cov
    - pip install nose
    
script:
    - py.test 
    - pwd
    - nosetests --nocapture
    
# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
    
notifications:
  email: false
    

