language: python
python:
    - "3.4"
before_install:
    - pip install pytest pytest-cov
    - pip install nose
    
script:
    - py.test 
    - pwd
    - nosetests --nocapture
    
# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
    
notifications:
  email: false
    

